# Generated by Django 4.2.24 on 2025-09-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_source_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
